### ISSUE TITLE
卡在 OnConnectionChanged Connecting

### ISSUE THREAD

**Issue by pluveto** [woodemi/notepad-paint-web#19]
开启设备和电脑的蓝牙之后, 点击扫描, 扫描到了设备, 点击连接, 显示正在连接, 之后就没反应了
debug输出:
```
_scanResultList: 
item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5item: WDMA5NotepadConnector::Connect
OnConnectionChanged Connecting
线程 0x920 已退出，返回值为 0 (0x0)。
线程 0x3724 已退出，返回值为 0 (0x0)。
引发的异常:“System.NullReferenceException”(位于 NotepadKitSample.exe 中)
**_notepadClient** 是 null。
```
用的是sample的代码, 只加了这几行:
```
Debug.WriteLine("_scanResultList: ");
            foreach (var item in _scanResultList.ToList())
            {
                var byteArray = item.ManufacturerData;
                Debug.WriteLine("item: " + System.Text.Encoding.ASCII.GetString(byteArray));
            }
```

**Comment by pluveto** [comment]
我想我已经找到了原因所在. OnConnectionChanged ( Demo 里) 的 else 部分, 你们把 _notepadClient 设为了 null, 我改成 if(_notepadClient==null)                    _notepadClient = sender; 这样之后就可以连接了. 但是貌似进行了两次连接.
```
OnConnectionStatusChanged 246639112742851, Connected
onCommandSend: 08-02
OnConnectionStatusChanged 246639112742851, Disconnected
未连接
OnConnectionChanged Disconnected
OnConnectionStatusChanged 246639112742851, Connected
onCommandSend: 01-0A-00-00-00-01
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 02-01
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 02-01
onCommandReceive: 02-01
OnConnectionChanged AwaitConfirm
onCommandReceive: 02-01
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-08-00-00-01
onCommandSend: 08-02
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-08-00-00-01
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 02-01
onCommandSend: 01-0A-00-00-00-01
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 02-01
OnConnectionChanged AwaitConfirm
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 03-00
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 03-00
onConfirmReceive: 03-00
onConfirmReceive: 03-00
OnConnectionChanged Connected
OnConnectionChanged Connected
onCommandSend: 05-00
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-05-00-00-00
onCommandReceive: 07-05-00-00-00
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-05-00-00-00
onCommandReceive: 07-05-00-00-00
onCommandSend: 05-00
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-05-00-00-00
OnCharacteristicValueChanged 57444e02-ba5e-f4ee-5ca1-eb1e5e4b1ce0, 07-05-00-00-00
```

**Comment by Sunbreak** [comment]
> 开启设备和电脑的蓝牙之后, 点击扫描, 扫描到了设备, 点击连接, 显示正在连接, 之后就没反应了
> debug输出:
> 
> ```
> _scanResultList: 
> item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�item: WDMA5�NotepadConnector::Connect
> OnConnectionChanged Connecting
> 线程 0x920 已退出，返回值为 0 (0x0)。
> 线程 0x3724 已退出，返回值为 0 (0x0)。
> 引发的异常:“System.NullReferenceException”(位于 NotepadKitSample.exe 中)
> **_notepadClient** 是 null。
> ```
> 
> 用的是sample的代码, 只加了这几行:
> 
> ```
> Debug.WriteLine("_scanResultList: ");
>             foreach (var item in _scanResultList.ToList())
>             {
>                 var byteArray = item.ManufacturerData;
>                 Debug.WriteLine("item: " + System.Text.Encoding.ASCII.GetString(byteArray));
>             }
> ```

你这是C#代码……是不是提交错误了？
有问题欢迎直接添加微信“woodemi”

**Comment by pluveto** [comment]
对不起啊，同时开了uwp和dart的两个页面，我提交的时候搞混了。不过sample给的确实有点小问题------------------ 原始邮件 ------------------
发件人: "Sunbreak"<notifications@github.com>
发送时间: 2020年1月9日(星期四) 中午12:55
收件人: "woodemi/notepad-paint-web"<notepad-paint-web@noreply.github.com>;
抄送: "pluveto"<reg@pluvet.com>;"Author"<author@noreply.github.com>;
主题: Re: [woodemi/notepad-paint-web] 卡在 OnConnectionChanged Connecting (#19)


 
开启设备和电脑的蓝牙之后, 点击扫描, 扫描到了设备, 点击连接, 显示正在连接, 之后就没反应了
 debug输出:
 _scanResultList:  item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 NotepadConnector::Connect OnConnectionChanged Connecting 线程 0x920 已退出，返回值为 0 (0x0)。 线程 0x3724 已退出，返回值为 0 (0x0)。 引发的异常:“System.NullReferenceException”(位于 NotepadKitSample.exe 中) **_notepadClient** 是 null。  
用的是sample的代码, 只加了这几行:
 Debug.WriteLine("_scanResultList: ");             foreach (var item in _scanResultList.ToList())             {                 var byteArray = item.ManufacturerData;                 Debug.WriteLine("item: " + System.Text.Encoding.ASCII.GetString(byteArray));             }   
你这是C#代码……是不是提交错误了？
 有问题欢迎直接添加微信“woodemi”
 
&mdash;

**Comment by Sunbreak** [comment]
> 对不起啊，同时开了uwp和dart的两个页面，我提交的时候搞混了。不过sample给的确实有点小问题------------------ 原始邮件 ------------------ 发件人: "Sunbreak"<notifications@github.com> 发送时间: 2020年1月9日(星期四) 中午12:55 收件人: "woodemi/notepad-paint-web"<notepad-paint-web@noreply.github.com>; 抄送: "pluveto"<reg@pluvet.com>;"Author"<author@noreply.github.com>; 主题: Re: [woodemi/notepad-paint-web] 卡在 OnConnectionChanged Connecting (#19) 开启设备和电脑的蓝牙之后, 点击扫描, 扫描到了设备, 点击连接, 显示正在连接, 之后就没反应了 debug输出: _scanResultList: item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 item: WDMA5 NotepadConnector::Connect OnConnectionChanged Connecting 线程 0x920 已退出，返回值为 0 (0x0)。 线程 0x3724 已退出，返回值为 0 (0x0)。 引发的异常:“System.NullReferenceException”(位于 NotepadKitSample.exe 中) **_notepadClient** 是 null。 用的是sample的代码, 只加了这几行: Debug.WriteLine("_scanResultList: "); foreach (var item in _scanResultList.ToList()) { var byteArray = item.ManufacturerData; Debug.WriteLine("item: " + System.Text.Encoding.ASCII.GetString(byteArray)); } 你这是C#代码……是不是提交错误了？ 有问题欢迎直接添加微信“woodemi” &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

恩恩，都是开源的，可以一起调整
